### ISSUE TITLE
swipedViewHolder.itemView - NPE

### ISSUE THREAD

**Issue by VivekThummar52** [meshileya/WaferSimpleApp#1]
`onTouch()` method In `SwipeHelper` gives a null pointer exception after removing an item from the list, in line `View swipedItem = swipedViewHolder.itemView;`, any solution?

**Comment by meshileya** [comment]
Hello @VivekThummar52 ...although, this seems to be an old project but I will check it out now and revert back in 30minutes time.

**Comment by VivekThummar52** [comment]
Okk, thank you very much!!

**Comment by meshileya** [comment]
Fixed already. 

The click listener was set to null.
Kindly confirm if this resolves your issue.

**Comment by VivekThummar52** [comment]
my current code for adding button is as given below:

    SwipeHelper swipeHelper = new SwipeHelper(context, recyclerView) {
            @Override
            public void instantiateUnderlayButton(RecyclerView.ViewHolder viewHolder, List<UnderlayButton> underlayButtons) {
                underlayButtons.add(new SwipeHelper.UnderlayButton(
                        "Delete",
                        0,
                        Color.parseColor("#5D5D5A"),
                        new SwipeHelper.UnderlayButtonClickListener() {
                            @Override
                            public void onClick(int pos) {
                                Preset preset = presetList.get(pos);
                                if (newPreset != null) {
                                    presetList.remove(pos);
                                    adapter.notifyDataSetChanged();
                                }
                            }
                        }
                ));
            }
        };
		
        swipeHelper.attachSwipe();


and i'm using old(i think) `SwipeHelper` class from this link: https://stackoverflow.com/a/45062745/10752962

what should i change in any of the class?

**Comment by meshileya** [comment]
have you gone through how it was implemented in this project?

**Comment by VivekThummar52** [comment]
not much more, i'm just using SwipeHelper class,
I think i have to look at whole project so that i can understand the problem..

**Comment by VivekThummar52** [comment]
Could that be the problem that I'm passing context while adding buttons using the method `underlayButtons.add(...)` because I just installed your application and make changes but still it works and on the other side, I replaced my code with your code and still the same crash occurs while I touch recycler view after deleting the item from the list

**Comment by meshileya** [comment]
can you upload your project and share it with me to run a test from my end?

**Comment by VivekThummar52** [comment]
Sorry for that bro, but let me explain the case to you, i have implemented `RecyclerView` in `BottomSheetDialogFragment` and implemented `swipe` event on it, for solving this bug i commented other code and now there is just item removing code from list.



    private RecyclerView recyclerView;
    private PresetListAdapter adapter;

    recyclerView = view.findViewById(R.id.recyclerView_preset);
    recyclerView.setLayoutManager(new LinearLayoutManager(context, RecyclerView.VERTICAL, false));
    presetList.addAll(...);

    adapter = new PresetListAdapter(context, presetList);
    recyclerView.setAdapter(adapter);


    NewSwipeHelper newSwipeHelper = new NewSwipeHelper(context, recyclerView) {
            @Override
            public void instantiateUnderlayButton(RecyclerView.ViewHolder viewHolder, List<UnderlayButton> underlayButtons) {
                underlayButtons.add(new NewSwipeHelper.UnderlayButton(
                        Color.parseColor("#9024a2"),
                        new UnderlayButtonClickListener() {
                            @Override
                            public void onClick(int pos) {
                                presetList.remove(pos);
                                adapter.notifyDataSetChanged();
                            }
                        }
                ));
            }
        };

        newSwipeHelper.attachSwipe();


and it looks like the problem is in `onTouch()` method in `SwipeHelper` class where `swipedPos` remained same even after item removal, let me explain you:
i have 3 items in list and i removed the last one means from index `2` and after removing it when i touch `recycler view` it shows `swipedpos = 2`. So, basically index 2 isn't there because i just removed it.

**Comment by VivekThummar52** [comment]
Ohk i just found same problem in your project also, just remove last item from list and touch on `recycler view` and app will be crash..

**Comment by VivekThummar52** [comment]
did you found any solution?

**Comment by meshileya** [comment]
hello, have you sorted it out? @VivekThummar52

**Comment by VivekThummar52** [comment]
no, i used another one for my requirement.
